language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

php:
  - 7.2
  - 7.1
  - 7.0

env:
  - ILLUMINATE_VERSION=5.6.*
  - ILLUMINATE_VERSION=5.5.*

matrix:
  fast_finish: true
  exclude:
    - php: 7.0
      env: ILLUMINATE_VERSION=5.6.*

before_script:
  - echo "${ILLUMINATE_VERSION}"
  - travis_retry composer install --prefer-source --no-interaction
  - composer require "illuminate/cache:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/queue:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/console:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/contracts:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/filesystem:${ILLUMINATE_VERSION}" --no-update
  - composer update

scripts:
  - php vendor/bin/phpunit -c phpunit.xml

notifications:
  email: false