language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  - ILLUMINATE_VERSION=5.5.*
  - ILLUMINATE_VERSION=5.6.*

matrix:
  fast_finish: true
  exclude:
    - php: 7.0
      env: ILLUMINATE_VERSION=5.6.*

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;
  - composer update

scripts:
  - phpunit